### ISSUE TITLE
error Couldn't find package "@fortawesome/fontawesome-free@^5.12.0" required by "@buffetjs/styles@3.0.5" on the "npm" registry.

### ISSUE THREAD

**Issue by kashem76** [strapi/community-content#414]
**The concerning content**

**
 
1) When I try to run the command "yarn create strapi-app backend" and choose all the options, then I get the following error:
`
error Couldn't find package "@fortawesome/fontawesome-free@^5.12.0" required by "@buffetjs/styles@3.0.5" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@fortawesome/fontawesome-free@^5.11.2" required by "strapi-admin@3.0.0-beta.20.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.25" required by "strapi-admin@3.0.0-beta.20.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-brands-svg-icons@^5.11.2" required by "strapi-admin@3.0.0-beta.20.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.25" required by "@buffetjs/core@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.22" required by "@buffetjs/styles@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.22" required by "@buffetjs/styles@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-free@^5.12.0" required by "@buffetjs/styles@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.25" required by "@buffetjs/core@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.11.2" required by "strapi-admin@3.0.0-beta.20.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.11.2" required by "@buffetjs/core@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.11.2" required by "@buffetjs/core@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.10.2" required by "@buffetjs/styles@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.10.2" required by "@buffetjs/styles@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.7" required by "strapi-admin@3.0.0-beta.20.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/core@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/core@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/styles@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/styles@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.11.2" required by "@buffetjs/core@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.11.2" required by "@buffetjs/core@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.10.2" required by "@buffetjs/styles@3.0.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.10.2" required by "@buffetjs/styles@3.0.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Nothing in the node_modules so 
yarn develop command does not work.

I tried to manually install stripi but got the same error as above

**

**Comment by ShadaW11** [comment]
Hello @kashem76 Could you please post your query on your [forum](http://forum.strapi.io) and we would be happy to help out. In our community content section is not used for support but rather for articles.
